name: ollama

services:
  ollama:
    image: ollama/ollama:rocm
    devices:
        - "/dev/kfd:/dev/kfd"
        - "/dev/dri:/dev/dri"
    ports:
        - 11434:11434
    volumes:
        - ./volumes/ollama:/root/.ollama
        - ./entrypoint.sh:/entrypoint.sh
    container_name: ollama
    pull_policy: always
    restart: always
    entrypoint: ["/usr/bin/bash", "/entrypoint.sh"]
    environment:
      - HSA_OVERRIDE_GFX_VERSION=10.3.0
      - HCC_AMDGPU_TARGET=gfx1030
      - LLM_EMBEDDING_MODEL=${LLM_EMBEDDING_MODEL}
      - LLM_GENERATION_MODEL=${LLM_GENERATION_MODEL}
    networks:
        - vimar_net

networks:
  vimar_net:
    external: true